### ISSUE TITLE
jobCleanup does not work on linux

### ISSUE THREAD

**Issue by speer** [electriccommunity/EC-Admin#21]
Step error [FormalParameterError]: missing parameter(s) to 'subJC_deleteWorkspace': winDir

Parameter winDir of subJC_deleteWorkspace is marked as required, but not present on linux systems

**Comment by lrochette** [comment]
I fixed the problem by marking this parameter as not required but I cannot reproduce the problem.
I've a workspace with no Windows path but even when passed as empty it does not fail. Not sure what is missing
Can you provide the fields for your workspace please

**Comment by speer** [comment]
![screen](https://cloud.githubusercontent.com/assets/2227144/6634687/3317f1f8-c95c-11e4-9fee-1d0c01652ca4.jpg)
marking the parameter as not required fixed the issue.
