### ISSUE TITLE
deleteObjects procedure fails with duplicate deletion

### ISSUE THREAD

**Issue by yafubark** [electriccommunity/EC-Admin#29]
The deleteObjects procedure generated the fopllowing weeor when trying to delete a batch of jobs.  Usually, the first chunk of jobs gets deleted and, during a subsequent chunk, a previous objectId gets returned as result of the deletedObjects call.

Chunk size: 100
Days limit: 514
Max objects: 1000
Object type: job
Poll interval: 5s

Waiting for 100 jobs to be deleted...
Deleted 100 jobs (10%) | Total average deletion time: 0.20s
Error: job-913417 is being deleted again

**Comment by yafubark** [comment]
EC 4.2.6 on RHEL 5.

**Comment by lrochette** [comment]
@yafubark Do you have another job deletion procedure running in parallel like jobsCleanup?

**Comment by yafubark** [comment]
No other job deletions currently running. We had the job cleanup that was written in-house using deleteJob but that was too slow.

**Comment by tanaynagjee** [comment]
Is it always job-913417?  I wonder if there's something going wrong while trying to delete a specific job.  I'd check the Commander server log to see if there are any suspicious errors during these deletes.

**Comment by yafubark** [comment]
That job is was just an example. The ids differ in each test.  I do not see any errors jumping out at me in the server logs.
