### ISSUE TITLE
projectAsCode fails if server and agent runs as different user accounts

### ISSUE THREAD

**Issue by kjonick** [electriccommunity/EC-Admin#30]
The projectAsCode procedure fails if the server and agent processes for Electric Commander are using different user accounts.  

The issue is that the export command in "exportProjectToServer" exports the file as the server user.  The rest of the procedure is run as the agent.  The "deleteExportedProject" has code to cleanup the file and does not have permission to do so.

The procedure does complete and the project is exported.  However, it does so with errors.  This is a supported configuration, so it would be good if this tool worked successfully in this case.

**Comment by lrochette** [comment]
This is a Commander design issue. The export is always done by the server account on the server itself. I'm checking internally what options are available.

**Comment by kjonick** [comment]
Thanks Laurent.  Let me know what you find out.  Our plan was to run server and agent as separate users, but we utilize the projectAsCode function heavily.  

I did fork a copy of this and added a checkbox parameter, then RunCondition around the deleteExport step.  This allows us to avoid this step.  It will re-run again successfully without removing the old version.  Let me know if something like that will work.  

Thanks!

**Comment by lrochette** [comment]
I think for now it's the easiest workaround.
I will implement it on my side as well so it's easier for you to merge

**Comment by nikhilv** [comment]
Ping / FYI @nparashar. This is the issue I talked to you in person about. In re: the server and agent running as different users and file cleanup.
