### ISSUE TITLE
deleteObjects procedure times out

### ISSUE THREAD

**Issue by yafubark** [electriccommunity/EC-Admin#35]
The deleteObjects procedure will throw this timeout error when the chunk size is large enough and the procedure is being run by admin.  This is EC 4.2.6 on RHEL 5.

Chunk size: 5000
Days limit: 421
Max objects: 20000
Object type: job
Poll interval: 60s

Waiting for 5000 jobs to be deleted...
agent.UJ5DFUAVVVDKNRCA.run-5339277-61515912 timeout: The command did not complete before the requested timeout. The command will run to completion on the server.

It appears that the default timeout for API calls is very short for the admin user.  I have seen this error in our homebrew procedures when running as admin.

**Comment by lrochette** [comment]
There is a global option for EC-Admin procedures in /server/EC-Admin/cleanup/config/timeout (Created automatically upon promotion). I will modify the deleteObject to use this property as well.

Your other better option in the meantime is to use a way smaller chunk. Try 500
