### ISSUE TITLE
Trouble using EC-Admin-2.7.0.262:deleteWorkspaceOrphans via schedule

### ISSUE THREAD

**Issue by bsaeng** [electriccommunity/EC-Admin#36]
I created a schedule to invoke deleteWorkspaceOrphans via installed plugin; and get this error.

Job error [NoSuchProperty]: invalid property path: Evaluating property '/myProject/scripts/jobTemplate' in job 'job_53253417996677002030067'
Found project 'My-Admin'
No such property: 'scripts'

Why would I need the plugin's properties also defined in my admin project? I've been instructed that's not how Commander resolves properties.

"Start in the property sheet for the project in which the current job step was defined. If the job step has nested procedure invocations, this is the project associated with the innermost nested procedure, for example, the project associated with /myProcedure/."

Thanks

**Comment by lrochette** [comment]
I think you have an old version because this issue has already been fixed.
Please update to the latest version.

You can also replace the Job Name Template for the deleteWorkspaceOrphans by:
$[/plugins[EC-Admin]/project/scripts/jobTemplate]
