### ISSUE TITLE
deleteObjects missing library for getP method

### ISSUE THREAD

**Issue by vijaybandari** [electriccommunity/EC-Admin#41]
Undefined subroutine &main::getP called at /tmp/ecmdrAgent/agent.BJ5Y4AQMIJATZ046.run-c7b10503-58da-11e5-80e0-00505625f614-c7f27acc-58da-11e5-8462-00505625f614.cmd line 34.

**Comment by lrochette** [comment]
Verified in 4.2.6 and 6.0.1

**Comment by lrochette** [comment]
Thanks for reporting
